/-
Copyright (c) 2026 selpo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: selpo
-/

import HahnKaplanskyRealClosedness.OmegaLimit.PositiveRecursion.Components

/-!
# Positive-limit generated data for omega tail arguments
-/

namespace HahnKaplanskyRealClosedness

noncomputable section

universe u v

namespace HahnField

variable (k : Type u) (Γ : Type v)
variable [Field k] [LinearOrder k] [IsStrictOrderedRing k]
variable [AddCommGroup Γ] [LinearOrder Γ] [IsOrderedAddMonoid Γ]

/-- Primitive limit-step input for the transfinite one-cluster route.

This exposes the exact datum consumed by `rootInMaximalIdeal_of_positiveLimitStepExists`: at every
successor-limit ordinal, a coherent chain below the ordinal can be extended to a coherent chain
at the ordinal.  The component-style inputs below are stronger, more checkable packages for
constructing this raw limit step. -/
def KOneClusterPositiveLimitStepHypothesis
    [IsRealClosed k] [DivisibleBy Γ ℕ] : Type _ :=
  ∀ {F : Polynomial (valuationSubring k Γ)}
    (_hsmall : ∀ i, i < 1 → F.coeff i ∈ IsLocalRing.maximalIdeal (valuationSubring k Γ))
    (_hunit : IsUnit (F.coeff 1)),
      (¬ RootInMaximalIdeal k Γ F) →
        ∀ {o : Ordinal.{v}} (_ho : Order.IsSuccLimit o),
          PositiveIioCoherentChainAtBelow k Γ o F →
            PositiveIioCoherentChainAt k Γ o F

/-- The raw limit-step function used by the positive Hartogs recursion for a fixed polynomial. -/
abbrev KOneClusterPositiveLimitStepData
    [IsRealClosed k] [DivisibleBy Γ ℕ]
    (F : Polynomial (valuationSubring k Γ)) : Type _ :=
  ∀ {o : Ordinal.{v}}, Order.IsSuccLimit o →
    PositiveIioCoherentChainAtBelow k Γ o F →
      PositiveIioCoherentChainAt k Γ o F

/-- Generated-recursion limit-step input for the transfinite one-cluster route.

This is weaker than `KOneClusterPositiveLimitStepHypothesis`: under the no-root assumption it asks
only for one limit-step function that can be used by `PositiveIioCoherentChainAt.recOfNoRoot`.
The actual Hartogs contradiction then runs on the generated chain.  Component packages such as
split-top data can still be used to construct this limit step, but they no longer need to be
stated for every abstract below-chain at the public endpoint. -/
def KOneClusterPositiveGeneratedLimitStepHypothesis
    [IsRealClosed k] [DivisibleBy Γ ℕ] : Prop :=
  ∀ {F : Polynomial (valuationSubring k Γ)}
    (_hsmall : ∀ i, i < 1 → F.coeff i ∈ IsLocalRing.maximalIdeal (valuationSubring k Γ))
    (_hunit : IsUnit (F.coeff 1)),
      (¬ RootInMaximalIdeal k Γ F) →
        Nonempty (KOneClusterPositiveLimitStepData k Γ F)

/-- Generated-chain compatibility package for constructing natural-bottom components.

This is the proof-facing boundary below generated natural-bottom components.  It fixes one
recursive limit-step function and asks only for the compatibility data on the chain generated by
that same function, rather than for split-top or natural-component data on arbitrary below-chains.
-/
structure KOneClusterPositiveGeneratedLimitStepCompatData
    [IsRealClosed k] [DivisibleBy Γ ℕ]
    {F : Polynomial (valuationSubring k Γ)}
    (hsmall : ∀ i, i < 1 → F.coeff i ∈ IsLocalRing.maximalIdeal (valuationSubring k Γ))
    (hunit : IsUnit (F.coeff 1))
    (hno : ¬ RootInMaximalIdeal k Γ F) where
  limitStep : KOneClusterPositiveLimitStepData k Γ F
  bot :
    ∀ {o : Ordinal} (ho : Order.IsSuccLimit o),
      let C := PositiveIioCoherentChainAt.recBelowOfNoRoot k Γ hsmall hunit hno limitStep ho
      { v₀ : Γ //
        C.succStageBotBlockNextValEq k Γ ho v₀ ∧
          ∀ i : Set.Iio o, (i : Ordinal) = 0 →
            (C.limitBlock k Γ ho i).next.val k Γ = v₀ }
  components :
    ∀ {o : Ordinal} (ho : Order.IsSuccLimit o),
      (PositiveIioCoherentChainAt.recBelowOfNoRoot k Γ hsmall hunit hno limitStep ho)
        |>.NaturalComponents k Γ ho

/-- Generated-recursion compatibility input for the transfinite one-cluster route. -/
def KOneClusterPositiveGeneratedLimitStepCompatHypothesis
    [IsRealClosed k] [DivisibleBy Γ ℕ] : Prop :=
  ∀ {F : Polynomial (valuationSubring k Γ)}
    (hsmall : ∀ i, i < 1 → F.coeff i ∈ IsLocalRing.maximalIdeal (valuationSubring k Γ))
    (hunit : IsUnit (F.coeff 1))
    (hno : ¬ RootInMaximalIdeal k Γ F),
      Nonempty
        (KOneClusterPositiveGeneratedLimitStepCompatData k Γ hsmall hunit hno)

/-- Generated-chain block-projection core data.

This is the weakest generated boundary currently exposed for the positive limit step: all
bottom-source and bottom-next obligations live only on the recursively generated chain. -/
structure KOneClusterPositiveGeneratedBlockProjectionCoreData
    [IsRealClosed k] [DivisibleBy Γ ℕ]
    {F : Polynomial (valuationSubring k Γ)}
    (hsmall : ∀ i, i < 1 → F.coeff i ∈ IsLocalRing.maximalIdeal (valuationSubring k Γ))
    (hunit : IsUnit (F.coeff 1))
    (hno : ¬ RootInMaximalIdeal k Γ F) where
  limitStep : KOneClusterPositiveLimitStepData k Γ F
  botSource :
    ∀ {o : Ordinal} (ho : Order.IsSuccLimit o),
      ∃ s₀ : valuationSubring k Γ,
        (PositiveIioCoherentChainAt.recBelowOfNoRoot
          k Γ hsmall hunit hno limitStep ho).BotSourceEq k Γ s₀ ∧
          (letI : OrderBot (Set.Iio o) := ordinalIioOrderBot ho
           ((PositiveIioCoherentChainAt.recBelowOfNoRoot
            k Γ hsmall hunit hno limitStep ho).limitState k Γ ho ⊥).source) = s₀
  bot :
    ∀ {o : Ordinal} (ho : Order.IsSuccLimit o),
      let C := PositiveIioCoherentChainAt.recBelowOfNoRoot k Γ hsmall hunit hno limitStep ho
      { v₀ : Γ //
        C.succStageBotBlockNextValEq k Γ ho v₀ ∧
          ∀ i : Set.Iio o, (i : Ordinal) = 0 →
            (C.limitBlock k Γ ho i).next.val k Γ = v₀ }
  components :
    ∀ {o : Ordinal} (ho : Order.IsSuccLimit o),
      (PositiveIioCoherentChainAt.recBelowOfNoRoot k Γ hsmall hunit hno limitStep ho)
        |>.BlockProjectionComponents k Γ ho

/-- Generated block-projection core input for the transfinite one-cluster route. -/
def KOneClusterPositiveGeneratedBlockProjectionCoreHypothesis
    [IsRealClosed k] [DivisibleBy Γ ℕ] : Prop :=
  ∀ {F : Polynomial (valuationSubring k Γ)}
    (hsmall : ∀ i, i < 1 → F.coeff i ∈ IsLocalRing.maximalIdeal (valuationSubring k Γ))
    (hunit : IsUnit (F.coeff 1))
    (hno : ¬ RootInMaximalIdeal k Γ F),
      Nonempty
        (KOneClusterPositiveGeneratedBlockProjectionCoreData k Γ hsmall hunit hno)

end HahnField

end

end HahnKaplanskyRealClosedness
